language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_d077ca11d031_key -iv $encrypted_d077ca11d031_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
